### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by AstraLuma** [GameWithPixels/PixelsWebDemo#1]
```
$ yarn build|cat
yarn run v1.22.19
$ preact build
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
 Build  [                    ] 0% (0.0s) compiling✖ ERROR Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/astraluma/src/pixels-dice/PixelsWebDemo/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/astraluma/src/pixels-dice/PixelsWebDemo/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/astraluma/src/pixels-dice/PixelsWebDemo/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/astraluma/src/pixels-dice/PixelsWebDemo/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/astraluma/src/pixels-dice/PixelsWebDemo/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/astraluma/src/pixels-dice/PixelsWebDemo/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/astraluma/src/pixels-dice/PixelsWebDemo/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/astraluma/src/pixels-dice/PixelsWebDemo/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/astraluma/src/pixels-dice/PixelsWebDemo/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/astraluma/src/pixels-dice/PixelsWebDemo/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/astraluma/src/pixels-dice/PixelsWebDemo/node_modules/babel-loader/lib/index.js:59:71
error Command failed with exit code 1.                                                                                                           
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Fedora Workstation 38
NodeJS v18.16.0
Yarn v1.22.19

**Comment by AstraLuma** [comment]
Following https://stackoverflow.com/a/69699772/2904824 :

* Downgrading to NodeJS 16 doesn't seem to do anything? But I'm not super confident the downgrade totally works
* Setting `$NODE_OPTIONS` produces a different error:

```
$ preact build
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

                  bundle.90223.css ⏤  605 B
               bundle.*****.esm.js ⏤  8.95 kB
            polyfills.*****.esm.js ⏤  2.18 kB
        route-home.chunk.39202.css ⏤  1.25 kB
     route-home.chunk.*****.esm.js ⏤  34 kB
    route-notfound.chunk.c2e10.css ⏤  65 B
 route-notfound.chunk.*****.esm.js ⏤  518 B
     route-profile.chunk.48073.css ⏤  88 B
  route-profile.chunk.*****.esm.js ⏤  437 B
                         sw-esm.js ⏤  11.1 kB
                             sw.js ⏤  11.1 kB
                   bundle.391b7.js ⏤  8.94 kB
                polyfills.f4816.js ⏤  2.28 kB
         route-home.chunk.967ed.js ⏤  45.1 kB
     route-notfound.chunk.67a2f.js ⏤  519 B
      route-profile.chunk.5d05c.js ⏤  951 B
                        index.html ⏤  381 B
                          200.html ⏤  381 B

✖ ERROR   Error: undefined:1:3135: @keyframes missing '{'
  
  - index.js:62 error
    [PixelsWebDemo]/[css]/lib/parse/index.js:62:15
  
  - index.js:303 atkeyframes
    [PixelsWebDemo]/[css]/lib/parse/index.js:303:25
  
  - index.js:534 atrule
    [PixelsWebDemo]/[css]/lib/parse/index.js:534:12
  
  - index.js:118 rules
    [PixelsWebDemo]/[css]/lib/parse/index.js:118:58
  
  - index.js:81 stylesheet
    [PixelsWebDemo]/[css]/lib/parse/index.js:81:21
  
  - index.js:565 module.exports [as parse]
    [PixelsWebDemo]/[css]/lib/parse/index.js:565:20
  
  - critters.js:35 parseStylesheet
    [PixelsWebDemo]/[critters-webpack-plugin]/dist/critters.js:35:16
  
  - critters.js:440 Critters.<anonymous>
    [PixelsWebDemo]/[critters-webpack-plugin]/dist/critters.js:440:19
  
  - new Promise
  
  - critters.js:424 Critters.processStyle
    [PixelsWebDemo]/[critters-webpack-plugin]/dist/critters.js:424:12
  
  - critters.js:233 
    [PixelsWebDemo]/[critters-webpack-plugin]/dist/critters.js:233:76
  
  - Array.map
  
  - critters.js:233 Critters.$If_3
    [PixelsWebDemo]/[critters-webpack-plugin]/dist/critters.js:233:39
  
  - critters.js:223 Critters.<anonymous>
    [PixelsWebDemo]/[critters-webpack-plugin]/dist/critters.js:223:34
  

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

EDIT: Uninstalling system nodes and using NVM instead produces the same error as above.

**Comment by obasille** [comment]
Hi!
I'm using Node 16 on Windows & MacOS. Just to be sure I did a fresh clone on both platforms and got it to build without error.

As you suggest it seems to be related to be using a version of NodeJS > 16, see this webpack [issue](
  https://github.com/webpack/webpack/issues/14532
 ). According to the discussion in this issue, a workaround is to add `NODE_OPTIONS=--openssl-legacy-provider`.
 
This project was created with [preact-cli](
  https://github.com/preactjs/preact-cli
) about a year ago.
As a comparison I've created a new project with the latest version of preact-cli and sure enough they have added the `--openssl-legacy-provider` option. I've updated the scripts commands accordingly.

I've also updated the packages, I hope it will work with NodeJS 18 now.

Note: as documented in the readme, the `dev` and `build` scripts don't work anymore with NodeJS 16, so I've added a  `dev16` and `build16` scripts.

**Comment by AstraLuma** [comment]
That resolved the initial error, but I'm still getting the [second error](https://github.com/GameWithPixels/PixelsWebDemo/issues/1#issuecomment-1608746636)

**Comment by obasille** [comment]
There are instances of `@keyframes` in the `/src/routes/home/style.css`, can you delete them and see if you still get build errors?

**Comment by obasille** [comment]
Passing `--no-inline-css` flag might resolve the issue.
https://github.com/preactjs/preact-cli#preact-build

**Comment by AstraLuma** [comment]
> Passing `--no-inline-css` flag might resolve the issue. https://github.com/preactjs/preact-cli#preact-build

Yup, that allows for a successful build, and it loads into my browser.

> There are instances of `@keyframes` in the `/src/routes/home/style.css`, can you delete them and see if you still get build errors?

This also builds and loads.

**Comment by obasille** [comment]
Great!
Still, I don't understand why you were getting this error... Was your `yarn.lock` modified locally? (meaning we're not running the exact same packages)

**Comment by AstraLuma** [comment]
> Was your `yarn.lock` modified locally?

Nope.

**Comment by obasille** [comment]
I have the same error on my system now, not sure why I didn't had it before (may be some package was not properly synced?).
Anyway I've updated the build command. Thanks a lot for your help!
